export enum PlaceFeatureEnum {
  WIFI = "wifi",
  PARKING = "parking",
  LIVE_MUSIC = "live_music",
  TERRACE = "terrace",
  KIDS_ZONE = "kids_zone",
  VEGAN = "vegan",
  PET_FRIENDLY = "pet_friendly",
  DELIVERY = "delivery",
  CARD_PAYMENT = "card_payment",
  AIR_CONDITIONING = "air_conditioning",
  SMOKING_AREA = "smoking_area",
  CRAFT_BEER = "craft_beer",
  KARAOKE = "karaoke",
  DANCE_FLOOR = "dance_floor",
  PROJECTOR = "projector",
  SPORTS_TV = "sports_tv",
  TAKEAWAY = "takeaway",
  WHEELCHAIR_ACCESS = "wheelchair_access",
}
