import dotenv from "dotenv";

dotenv.config();

export const envConfig = {
  APP_PORT: process.env.APP_PORT,
  APP_HOST: process.env.APP_HOST,

  MONGO_URI: process.env.MONGO_URI || "",

  APP_FRONT_URL: process.env.APP_FRONT_URL,

  JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
  JWT_ACCESS_EXPIRATION: process.env.JWT_ACCESS_EXPIRATION,
  JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
  JWT_REFRESH_EXPIRATION: process.env.JWT_REFRESH_EXPIRATION,

  ACTION_VERIFY_EMAIL_SECRET: process.env.ACTION_VERIFY_EMAIL_SECRET,
  ACTION_VERIFY_EMAIL_EXPIRATION: process.env.ACTION_VERIFY_EMAIL_EXPIRATION,
  ACTION_FORGOT_PASSWORD_SECRET: process.env.ACTION_FORGOT_PASSWORD_SECRET,
  ACTION_FORGOT_PASSWORD_EXPIRATION:
    process.env.ACTION_FORGOT_PASSWORD_EXPIRATION,
  ACTION_ACCOUNT_RESTORE_SECRET: process.env.ACTION_ACCOUNT_RESTORE_SECRET,
  ACTION_ACCOUNT_RESTORE_EXPIRATION:
    process.env.ACTION_ACCOUNT_RESTORE_EXPIRATION,

  SMTP_EMAIL: process.env.SMTP_EMAIL,
  SMTP_PASSWORD: process.env.SMTP_PASSWORD,

  OLD_PASSWORD_EXPIRATION: process.env.OLD_PASSWORD_EXPIRATION,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
};
